steps:
    - command: "swift build"
    - command: "swift test --enable-code-coverage"
    - command: "cd Demo; xcodebuild clean -scheme SwiftGLTFDemo -destination 'generic/platform=macOS'"
    - command: "cd Demo; xcodebuild -scheme SwiftGLTFDemo -allowProvisioningUpdates -destination 'generic/platform=macOS'"
    - command: "cd Demo; xcodebuild clean -scheme SwiftGLTFDemo -destination 'generic/platform=iOS'"
    - command: "cd Demo; xcodebuild -scheme SwiftGLTFDemo -allowProvisioningUpdates -destination 'generic/platform=iOS'"
